WebApp/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApp/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class AuthenticationController : Controller
    {
        // GET: Authentication
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(tbl_User user)
        {
            WebAppEntities db = new WebAppEntities();
            db.tbl_User.Add(user);
            db.SaveChanges();
            return RedirectToAction("UserList");
        }

        //public ActionResult UserList(string SortOrder, string SortBy,int PageNumber=1)
        //{
        //    WebAppEntities db = new WebAppEntities();

        //    ViewBag.SortOrder = SortOrder;
        //    ViewBag.SortBy = SortBy;
           

        //    var userList = db.tbl_User.ToList();


        //    //Call bellow method
        //    ApplySorting(SortOrder, SortBy, userList);
        //    userList = ApplyPagination(userList, PageNumber);

        //    //Ata sudu Acending & Decending er jonno

        //    //switch (SortOrder)
        //    //{
        //    //    case "Asc":
        //    //        {
        //    //            userList = userList.OrderBy(x => x.UserName).ToList();
        //    //            break;
        //    //        }
        //    //    case "Desc":
        //    //        {
        //    //            userList = userList.OrderByDescending(x => x.UserName).ToList();
        //    //            break;
        //    //        }
        //    //    default:
        //    //        {
        //    //            userList = userList.OrderBy(x => x.UserName).ToList();
        //    //            break;
        //    //        }
        //    //}




        //    //userList = userList.Skip(2).ToList();  //first jotota skip kortea cai tar jonno ai condition ta (Paignation)
        //    //userList = userList.Skip(2).Take(1).ToList();
        //    //userList = userList.Take(1).ToList();

        //    ViewBag.TotalPages = Math.Ceiling(userList.Count() / 2.0);

        //    ViewBag.PageNumber = PageNumber;



        //    // userList = userList.Skip((PageNumber-1)*2).Take(1).ToList();
        //    userList = userList.Take(3).ToList();
        //    //Skip somikoron
        //    //1-1=0*2=0
        //    //2-1=1*2=2
            
            
        //    return View(userList);
        //}

        //[HttpPost]
        //public ActionResult UserList(string searchText)
        //{
        //    WebAppEntities db = new WebAppEntities();
        //    var userList = db.tbl_User.ToList();

        //    if (searchText !=null)
        //    {
        //        //userList = db.tbl_User.Where(x => x.UserName == searchText).ToList(); //ata holo exect match show er jonno means jeta search korbo seta asbe
        //        userList = db.tbl_User.Where(x => x.UserName.Contains(searchText) || x.Email.Contains(searchText) || x.Password.Contains(searchText)).ToList();  //ata holo a likle all a show korbe

        //    }

        //    return View(userList);
        //}

        public void ApplySorting(string SortOrder, string SortBy, List<tbl_User> userList)
        {

            //ATA JOTO GULA ROW THAKBE SETAR ASCENDING OR DECENDING ER JONNO (Searcing)

            switch (SortBy)
            {
                case "UserName":
                    {
                        switch (SortOrder)
                        {
                            case "Asc":
                                {
                                    userList = userList.OrderBy(x => x.UserName).ToList();
                                    break;
                                }
                            case "Desc":
                                {
                                    userList = userList.OrderByDescending(x => x.UserName).ToList();
                                    break;
                                }
                            default:
                                {
                                    userList = userList.OrderBy(x => x.UserName).ToList();
                                    break;
                                }
                        }
                        break;
                    }
                case "Email":
                    {
                        switch (SortOrder)
                        {
                            case "Asc":
                                {
                                    userList = userList.OrderBy(x => x.Email).ToList();
                                    break;
                                }
                            case "Desc":
                                {
                                    userList = userList.OrderByDescending(x => x.Email).ToList();
                                    break;
                                }
                            default:
                                {
                                    userList = userList.OrderBy(x => x.Email).ToList();
                                    break;
                                }
                        }
                        break;

                    }
                case "Password":
                    {
                        switch (SortOrder)
                        {
                            case "Asc":
                                {
                                    userList = userList.OrderBy(x => x.Password).ToList();
                                    break;
                                }
                            case "Desc":
                                {
                                    userList = userList.OrderByDescending(x => x.Password).ToList();
                                    break;
                                }
                            default:
                                {
                                    userList = userList.OrderBy(x => x.Password).ToList();
                                    break;
                                }
                        }
                        break;
                    }
                case "Gender":
                    {
                        switch (SortOrder)
                        {
                            case "Asc":
                                {
                                    userList = userList.OrderBy(x => x.Gender).ToList();
                                    break;
                                }
                            case "Desc":
                                {
                                    userList = userList.OrderByDescending(x => x.Gender).ToList();
                                    break;
                                }
                            default:
                                {
                                    userList = userList.OrderByDescending(x => x.Gender).ToList();
                                    break;
                                }
                        }
                        break;
                    }
                default:
                    {
                        userList = userList.OrderBy(x => x.UserName).ToList();
                        break;
                    }
            }
        }
        
        
        public List<tbl_User> ApplyPagination(List<tbl_User> userList, int PageNumber = 1)
        {
            ViewBag.TotalPages = Math.Ceiling(userList.Count() / 2.0);

            ViewBag.PageNumber = PageNumber;

            userList = userList.Take(3).ToList();
            return userList;
        }
        
       
        
        
        
        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]  //ata line er mane holo ata get & post both method er kaj korbe
        public ActionResult UserList(string searchText, string SortOrder, string SortBy, int PageNumber = 1)
        {
            WebAppEntities db = new WebAppEntities();
            ViewBag.SortOrder = SortOrder;
            ViewBag.SortBy = SortBy;
            var userList = db.tbl_User.ToList();
            if (searchText !=null)
            {
                userList = db.tbl_User.Where(x => x.UserName.Contains(searchText) || x.Email.Contains(searchText) || x.Password.Contains(searchText)).ToList();
                ApplySorting(SortOrder, SortBy, userList);
                userList = ApplyPagination(userList, PageNumber);
            }
            else
            {
                ApplySorting(SortOrder, SortBy, userList);
                userList = ApplyPagination(userList, PageNumber);
            }
            return View(userList);
        }




        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(tbl_User objuser)
        {
            WebAppEntities db = new WebAppEntities();
            var user = db.tbl_User.Where(x=>x.UserName == objuser.UserName && x.Password == objuser.Password).Count(); //FirstOrDefault() hole nicea (user !=null) ai condition ta hobe

            if (user > 0)
            {
                return RedirectToAction("UserList");
            }
            else
            {
                return View();
            }
        }

        public ActionResult UserProfile(int id)
        {
            WebAppEntities db = new WebAppEntities();
            var userlist = db.tbl_User.Find(id);

            //ata jokon checkbox null thakbe tokon data get korar jonno
            userlist.IsInterestInCsharp = (userlist.IsInterestInCsharp ==null) ? false : userlist.IsInterestInCsharp;
            userlist.IsInterestInJava = (userlist.IsInterestInJava == null) ? false : userlist.IsInterestInJava;
            userlist.IsInterestInPython = (userlist.IsInterestInPython == null) ? false : userlist.IsInterestInPython;


            //ata dropdown er jonno

WebApp/Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class CrudController : Controller
    {
        // GET: Crud
        public ActionResult Create()
        {
            return View();
        }

        //[HttpPost]
        //public ActionResult Create(string name, string description) //string name, string description ai paramitter er maddome view thakea controller a data patano hoicea.
        //{
        //    //ViewBag er maddome view a data patano hoicea
        //    ViewBag.name = name;  
        //    ViewBag.description = description;
        //    return View();
        //}


        [HttpPost]
        public ActionResult Create(tbl_Category category) 
        {
            WebAppEntities db = new WebAppEntities();
            db.tbl_Category.Add(category);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult List()
        {
            WebAppEntities db = new WebAppEntities();
            var list = db.tbl_Category.ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            WebAppEntities db = new WebAppEntities();
            var category = db.tbl_Category.Find(id);
            return View(category);
        }

        [HttpPost]
        public ActionResult Edit(tbl_Category category)
        {
            WebAppEntities db = new WebAppEntities();
            db.Entry(category).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("List");

        }

        public ActionResult Delete(int CategoryId)
        {
            WebAppEntities db = new WebAppEntities();
            var category = db.tbl_Category.Find(CategoryId);
            db.tbl_Category.Remove(category);
            db.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

WebApp/Controllers/Product_ValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class Product_ValidationController : Controller
    {
        WebAppEntities db = new WebAppEntities();
        // GET: Product_Validation
        public ActionResult Index()
        {

            var list = db.tbl_Product.ToList();
            return View(list);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(tbl_Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.tbl_Product.Add(product);
                    db.SaveChanges();

                    TempData["msg"] = "Product Added Successfully";

                    return RedirectToAction("Create");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception e)
            {
                TempData["msg"] = "Product Added Failed" + e.Message;
                return RedirectToAction("Create");
            }
          
        }
    }
}

WebApp/Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Admin Dashboard", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Main_Layout", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Create_Category", "Create", "Crud")</li>
                    <li>@Html.ActionLink("CategoryList", "List", "Crud")</li>
                    <li>@Html.ActionLink("UserList", "UserList", "Authentication")</li>
                    <li>@Html.ActionLink("Create_Product", "Create", "Product_Validation")</li>
                    <li>@Html.ActionLink("Product_List", "Index", "Product_Validation")</li>
                    

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Login", "Login", "Authentication")</li>
                    <li>@Html.ActionLink("Register", "Register", "Authentication")</li>
                    <li>@Html.ActionLink("Admin_Layout", "Index", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>